import {declareIndexPlugin, ReactRNPlugin} from "@remnote/plugin-sdk";

export const [TABLE, WIDTH] = ["table", "width"];

let TableCSS = ``;

async function onActivate(plugin: ReactRNPlugin) {
  await fetch("https://raw.githubusercontent.com/browneyedsoul/RemNote-ModernTableRow/main/src/snippet.css")
    .then((response) => response.text())
    .then((text) => {
      TableCSS = text;
      console.log(TableCSS);
    })
    .catch((error) => console.error(error));
  await plugin.app.registerCSS("rem-tree", TableCSS);
  await plugin.app.registerPowerup("Table", TABLE, "Attribute Column Width", {
    slots: [
      {
        code: "tableheader",
        name: "TH",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "table90",
        name: "Table90",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "table120",
        name: "Table120",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "table150",
        name: "Table150",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "table180",
        name: "Table180",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "table210",
        name: "Table210",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "table240",
        name: "Table240",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "table270",
        name: "Table270",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "table300",
        name: "Table300",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "table330",
        name: "Table330",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "table360",
        name: "Table360",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "table390",
        name: "Table390",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "table420",
        name: "Table420",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "table450",
        name: "Table450",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "table480",
        name: "Table480",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "table510",
        name: "Table510",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "table540",
        name: "Table540",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "table570",
        name: "Table570",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "table600",
        name: "Table600",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "table630",
        name: "Table630",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "table660",
        name: "Table660",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "table690",
        name: "Table690",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "table720",
        name: "Table720",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "table750",
        name: "Table750",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "table780",
        name: "Table780",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "table810",
        name: "Table810",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "table840",
        name: "Table840",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "table870",
        name: "Table870",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "table900",
        name: "Table900",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "table930",
        name: "Table930",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "table960",
        name: "Table960",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "table990",
        name: "Table990",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "table1020",
        name: "Table1020",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "table1050",
        name: "Table1050",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "table1080",
        name: "Table1080",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "table1110",
        name: "Table1110",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "table1140",
        name: "Table1140",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "table1170",
        name: "Table1170",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "table1200",
        name: "Table1200",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
    ],
  });

  await plugin.app.registerPowerup("Width", WIDTH, "Global Column Width", {
    slots: [
      {
        code: "w100",
        name: "W100",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "w200",
        name: "W200",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "w300",
        name: "W300",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "w400",
        name: "W400",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "w500",
        name: "W500",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "w600",
        name: "W600",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "w700",
        name: "W700",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "w800",
        name: "W800",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "w900",
        name: "W900",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "w1000",
        name: "W1000",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c1w100",
        name: "C1W100",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c2w100",
        name: "C2W100",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c3w100",
        name: "C3W100",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c4w100",
        name: "C4W100",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c5w100",
        name: "C5W100",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c6w100",
        name: "C6W100",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c7w100",
        name: "C7W100",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c8w100",
        name: "C8W100",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c9w100",
        name: "C9W100",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c1w200",
        name: "C1W200",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c2w200",
        name: "C2W200",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c3w200",
        name: "C3W200",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c4w200",
        name: "C4W200",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c5w200",
        name: "C5W200",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c6w200",
        name: "C6W200",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c7w200",
        name: "C7W200",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c8w200",
        name: "C8W200",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c9w200",
        name: "C9W200",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c1w300",
        name: "C1W300",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c2w300",
        name: "C2W300",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c3w300",
        name: "C3W300",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c4w300",
        name: "C4W300",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c5w300",
        name: "C5W300",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c6w300",
        name: "C6W300",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c7w300",
        name: "C7W300",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c8w300",
        name: "C8W300",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c9w300",
        name: "C9W300",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c1w400",
        name: "C1W400",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c2w400",
        name: "C2W400",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c3w400",
        name: "C3W400",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c4w400",
        name: "C4W400",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c5w400",
        name: "C5W400",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c6w400",
        name: "C6W400",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c7w400",
        name: "C7W400",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c8w400",
        name: "C8W400",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c9w400",
        name: "C9W400",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c1w500",
        name: "C1W500",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c2w500",
        name: "C2W500",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c3w500",
        name: "C3W500",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c4w500",
        name: "C4W500",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c5w500",
        name: "C5W500",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c6w500",
        name: "C6W500",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c7w500",
        name: "C7W500",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c8w500",
        name: "C8W500",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c9w500",
        name: "C9W500",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c1w600",
        name: "C1W600",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c2w600",
        name: "C2W600",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c3w600",
        name: "C3W600",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c4w600",
        name: "C4W600",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c5w600",
        name: "C5W600",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c6w600",
        name: "C6W600",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c7w600",
        name: "C7W600",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c8w600",
        name: "C8W600",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c9w600",
        name: "C9W600",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c1w700",
        name: "C1W700",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c2w700",
        name: "C2W700",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c3w700",
        name: "C3W700",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c4w700",
        name: "C4W700",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c5w700",
        name: "C5W700",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c6w700",
        name: "C6W700",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c7w700",
        name: "C7W700",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c8w700",
        name: "C8W700",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c9w700",
        name: "C9W700",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c1w800",
        name: "C1W800",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c2w800",
        name: "C2W800",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c3w800",
        name: "C3W800",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c4w800",
        name: "C4W800",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c5w800",
        name: "C5W800",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c6w800",
        name: "C6W800",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c7w800",
        name: "C7W800",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c8w800",
        name: "C8W800",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c9w800",
        name: "C9W800",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c1w900",
        name: "C1W900",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c2w900",
        name: "C2W900",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c3w900",
        name: "C3W900",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c4w900",
        name: "C4W900",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c5w900",
        name: "C5W900",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c6w900",
        name: "C6W900",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c7w900",
        name: "C7W900",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c8w900",
        name: "C8W900",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
      {
        code: "c9w900",
        name: "C9W900",
        onlyProgrammaticModifying: true,
        hidden: true,
      },
    ],
  });
}

async function onDeactivate(_: ReactRNPlugin) {}

declareIndexPlugin(onActivate, onDeactivate);
